In [15]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

In [ ]:
def make_timedelta(df, col):
    df['seconds'] = df[col]
    df[col] = pd.to_timedelta(df[col], unit='s')

In [28]:
size = "50Mb"

prefixes = ["blast_default", "blast", "last", "lastz", "stellar", "dist_stellar", "valik"]
table_df = pd.DataFrame([0, 0.02, 0.04, 0.06, 0.08, 0.1])
for prefix in prefixes:
    df = pd.read_csv("simulated/" + size + "/" + prefix + "_table1.tsv", sep = "\t")
    table_df[prefix + "_time"] = pd.to_timedelta(df["search time (sec)"], unit = 's')
    table_df[prefix + "_missed"] = df["missed (%)"]

table_df

,0,blast_default_time,blast_default_missed,blast_time,blast_missed,last_time,last_missed,lastz_time,lastz_missed,stellar_time,stellar_missed,dist_stellar_time,dist_stellar_missed,valik_time,valik_missed
0,0.00,0 days 00:00:09.516000,0.000,0 days 00:00:07.974000,0.002,0 days 00:03:23.947000,0.0,0 days 00:28:39.290000,0.0,0 days 00:01:10.744000,0.0,0 days 00:00:09.360000,0.0,0 days 00:00:05.232000,0.001
1,0.02,0 days 00:00:09.020000,0.002,0 days 00:00:09.497000,0.000,0 days 00:03:24.166000,0.0,0 days 00:29:16.536000,0.0,0 days 00:01:21.076000,0.0,0 days 00:00:10.180000,0.0,0 days 00:00:05.782000,0.000
2,0.04,0 days 00:00:08.976000,0.036,0 days 00:00:22.734000,0.000,0 days 00:03:24.290000,0.0,0 days 00:30:53.604000,0.0,0 days 00:00:12.880000,0.0,0 days 00:00:07.452000,0.0,0 days 00:00:03.350000,0.008
3,0.06,0 days 00:00:08.883000,0.132,0 days 00:03:06.761000,0.000,0 days 00:02:59.123000,0.0,0 days 00:29:05.444000,0.0,0 days 00:02:34.960000,0.0,0 days 00:00:12.236000,0.0,0 days 00:00:06.324000,0.000
4,0.08,0 days 00:00:08.672000,0.290,0 days 00:50:45.272000,0.000,0 days 00:04:00.093000,0.0,0 days 00:28:38.317000,0.0,0 days 07:27:35.622000,0.0,0 days 00:27:39.406000,0.0,0 days 00:01:10.215000,0.000
5,0.10,0 days 00:00:08.398000,0.470,0 days 02:13:54.144000,0.000,0 days 00:02:59.186000,0.0,0 days 00:28:48.531000,0.0,0 days 10:39:07.988000,0.0,0 days 00:38:08.953000,0.0,0 days 00:01:32.578000,0.003